/**
 * M01 ACCEPTANCE: real .xlsx files on a real filesystem -> deterministic operator pipeline -> real chart.
 * These are NOT simulated: the workbooks are genuine xlsx produced by openpyxl, read by our dependency-free
 * parser, analyzed, and charted. Rasterization to PNG is validated out-of-band (cairosvg here; qlmanage on
 * the Mac). Fixtures live under /tmp/mac_home (generated by the harness before this suite runs).
 */
import { describe, it, expect } from "vitest";
import { readFileSync, existsSync, statSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { analyzeWorkbookToChart, rankCandidates, type Candidate } from "../../src/mac/operator.js";

const HOME = "/tmp/mac_home";
const haveFixtures = existsSync(HOME);

/** Real recursive filesystem search (stands in for the helper's Spotlight/mdfind on macOS). */
function findWorkbooks(root: string, requested: string): Candidate[] {
  const out: Candidate[] = [];
  const walk = (dir: string) => {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      const p = join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else if (/\.(xlsx|xlsm|xls)$/i.test(e.name)) { const st = statSync(p); out.push({ path: p, name: e.name, size: st.size, mtimeMs: st.mtimeMs }); }
    }
  };
  walk(root);
  return rankCandidates(out, requested);
}

function run(requested: string, root = HOME) {
  const cands = findWorkbooks(root, requested);
  expect(cands.length).toBeGreaterThan(0);                 // SEARCH verify: a candidate exists
  const chosen = cands[0]!;
  expect(existsSync(chosen.path)).toBe(true);               // candidate readable
  const bytes = readFileSync(chosen.path);
  return analyzeWorkbookToChart(chosen, bytes, "Altarum pricing case");
}

describe.skipIf(!haveFixtures)("M01_real_mac_excel_to_chart", () => {
  it("MAIN: finds, parses, detects a real trend, and generates a real chart — no questions", () => {
    const r = run("Altarum_Pricing_Case_Template");
    expect(r.ok).toBe(true);
    // verification trace present and all green
    expect(r.stages.map((s) => s.stage)).toEqual(["search", "parse", "detect_series", "chart"]);
    expect(r.stages.every((s) => s.ok)).toBe(true);
    // used REAL values: Unit Price series, time-ordered, 12 points
    expect(r.pick!.valueColumn).toMatch(/price/i);
    expect(r.pick!.isTimeLike).toBe(true);
    expect(r.pick!.points).toBe(12);
    // real chart artifact content
    expect(r.svg!).toContain("<svg");
    expect(r.svg!).toContain("trend:");                     // trendline rendered
    expect(r.svg!.length).toBeGreaterThan(1000);
  });

  it("M01-A: workbook in Downloads", () => { expect(run("Altarum_Pricing_Case_Template", join(HOME, "Downloads")).ok).toBe(true); });
  it("M01-B: workbook on Desktop", () => { expect(run("Altarum_Pricing_Case_Template", join(HOME, "Desktop")).ok).toBe(true); });
  it("M01-C: nested Documents folder", () => { const r = run("Altarum_Pricing_Case_Template", join(HOME, "Documents")); expect(r.ok).toBe(true); });
  it("M01-D: approximate filename still matches", () => {
    const cands = findWorkbooks(join(HOME, "Downloads"), "altarum pricing case template");
    expect(cands[0]!.name).toMatch(/Altarum/i);
  });
  it("M01-E: two similar files — a plausible one is chosen deterministically", () => {
    const cands = findWorkbooks(join(HOME, "Downloads"), "Altarum_Pricing_Case_Template");
    expect(cands[0]!.name).toMatch(/Altarum_Pricing_Case_Template/i);  // exact-stem beats _old/_new variants
    const r = run("Altarum_Pricing_Case_Template", join(HOME, "Downloads"));
    expect(r.ok).toBe(true);
  });
  it("M01-F/G: multi-sheet workbook with formulas parses and charts", () => {
    const r = run("multi_sheet_formulas", join(HOME, "Documents"));
    expect(r.ok).toBe(true);
    expect(r.pick!.points).toBeGreaterThanOrEqual(2);
  });
  it("M01-H: no time dimension -> returns a valid categorical chart and says why", () => {
    const r = run("regions_no_time", join(HOME, "Documents"));
    expect(r.ok).toBe(true);
    expect(r.pick!.isTimeLike).toBe(false);                 // correctly NOT a trend
    expect(r.svg!).toContain("<rect");                      // bar chart
    expect(r.message).toMatch(/bar chart/i);
  });

  it("does not destructively modify the workbook (read-only bytes)", () => {
    const p = join(HOME, "Downloads", "Altarum_Pricing_Case_Template.xlsx");
    const before = statSync(p).size;
    run("Altarum_Pricing_Case_Template", join(HOME, "Downloads"));
    expect(statSync(p).size).toBe(before);                  // untouched
  });
});
